PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL,
 password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'student' CHECK(role IN ('student','staff','admin')),
 department TEXT NOT NULL DEFAULT 'CSE', year TEXT DEFAULT '1st', home_area TEXT DEFAULT 'BBDNITM Campus',
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS transport_modes (
 id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT UNIQUE NOT NULL, name TEXT NOT NULL,
 speed_kmh REAL NOT NULL, cost_per_km REAL NOT NULL, fixed_cost REAL NOT NULL DEFAULT 0,
 co2_kg_per_km REAL NOT NULL, calories_per_km REAL NOT NULL DEFAULT 0, shared_capacity INTEGER NOT NULL DEFAULT 1,
 source TEXT NOT NULL, assumption TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS trip_log (
 id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, mode_id INTEGER NOT NULL,
 origin TEXT NOT NULL, destination TEXT NOT NULL, distance_km REAL NOT NULL, duration_min REAL NOT NULL,
 co2_kg REAL NOT NULL, co2_saved_kg REAL NOT NULL, money_saved REAL NOT NULL, calories REAL NOT NULL DEFAULT 0,
 started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, weather TEXT DEFAULT '', aqi REAL DEFAULT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(mode_id) REFERENCES transport_modes(id)
);
CREATE INDEX IF NOT EXISTS idx_trip_user_date ON trip_log(user_id,started_at);
CREATE INDEX IF NOT EXISTS idx_trip_mode ON trip_log(mode_id);
CREATE INDEX IF NOT EXISTS idx_trip_route ON trip_log(origin,destination);
CREATE TABLE IF NOT EXISTS badges (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, icon TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_badges (user_id INTEGER NOT NULL,badge_id INTEGER NOT NULL,earned_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,badge_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(badge_id) REFERENCES badges(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS challenges (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT NOT NULL,target REAL NOT NULL,reward_points INTEGER NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS carpool_posts (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('driver','rider')),origin TEXT NOT NULL,destination TEXT NOT NULL,origin_lat REAL,origin_lon REAL,dest_lat REAL,dest_lon REAL,depart_at TEXT NOT NULL,seats INTEGER DEFAULT 1,status TEXT DEFAULT 'open',created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS carpool_requests (id INTEGER PRIMARY KEY AUTOINCREMENT,post_id INTEGER NOT NULL,rider_id INTEGER NOT NULL,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(post_id,rider_id),FOREIGN KEY(post_id) REFERENCES carpool_posts(id) ON DELETE CASCADE,FOREIGN KEY(rider_id) REFERENCES users(id) ON DELETE CASCADE);
